### ISSUE TITLE
Outline steps for testing out guide

### ISSUE THREAD

**Issue by maxrjones** [ESIPFed/esds-community-guide#16]
This would be a new section, which would outline the steps for testing and refining the community guide.

Some potential starting points:
1. Identify one existing or new open source software project within ESDS
2. Ask them to review the guide and try out some of the recommendation
3. Receive feedback
4. Open issues with potential changes to the guide based on the feedback
5. Identify a volunteer for revising the guide according to the feedback
6. Review the volunteer's revisions to the guide

**Comment by maxrjones** [comment]
Juanisa will address this issue.

**Comment by jjmccoy** [comment]
Putting here for future contributors to brainstorm and collaborate on:

**Community Member(s) - Internal**

1. Set up a schedule on when to review the guide periodically
2. Identify one existing or new open-source software project within ESDS
3. Ask the group to review the guide and test a sample of recommendations
4. The group provides feedback
5. Review the current feedback
6. Open issues with potential changes to the guide based on the feedback
7. Identify a group member to revise the guide according to the feedback
8. The group member completes the suggestions
9. Review the contributor’s revisions to the guide
10. Merge changes to the guide

**Community Contributor(s) - External**

1. Community contributor submits an issue in one of ESDS’ open-source software projects
2. The group reviews the issue and delegates on which/all changes to apply
3. Create a pull request (PR) from that issue
4. Identify a group member to revise the guide according to the feedback
5. The group member completes the suggestions
6. Review the changes in the PR
7. Merge changes to the guide
8. Closes out the issue
