### ISSUE TITLE
Build section on pull request and issue templates

### ISSUE THREAD

**Issue by maxrjones** [ESIPFed/esds-community-guide#17]
The current section on templates is currently empty. We should add an overview of templates for PRs and issues along with some examples. Should we remove the emails portion?

Resources for getting started - 

- [GitHub docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates)
- Xarray's issue templates - https://github.com/pydata/xarray/tree/main/.github/ISSUE_TEMPLATE
- Xarray's PR template - https://github.com/pydata/xarray/blob/main/.github/PULL_REQUEST_TEMPLATE.md

**Comment by maxrjones** [comment]
Juanisa plans to look at this issue.

**Comment by jjmccoy** [comment]
@maxrjones submitted PR #27.

**Comment by maxrjones** [comment]
Merged #27, thanks Juanisa!
