### ISSUE TITLE
Add revisions to tools section

### ISSUE THREAD

**Issue by maxrjones** [ESIPFed/esds-community-guide#22]
Juanisa's made great progress on the tools section. It would be fantastic to incorporate those into the guide.

**Comment by jjmccoy** [comment]
@jjmccoy Will get a PR up this week.

**Comment by jjmccoy** [comment]
@maxrjones submitted PR: https://github.com/ESIPFed/esds-community-guide/pull/26

**Comment by maxrjones** [comment]
Thanks for submitting the PR!

**Comment by jjmccoy** [comment]
PR is merged.

**Comment by maxrjones** [comment]
Thanks again @jjmccoy!
