### ISSUE TITLE
Expand success stories

### ISSUE THREAD

**Issue by maxrjones** [ESIPFed/esds-community-guide#23]
It would be great to add more success stories, expanding on the Pangeo example. Some possibilities:
- STAC
- GMT
- NASA TOPS
- Apache

**Comment by maxrjones** [comment]
Holly will add NASA TOPS section and Nga will add Apache

**Comment by asteiker** [comment]
@maxrjones [earthaccess](https://github.com/nsidc/earthaccess) is another great success story. Can we contribute to this through a new branch?

**Comment by maxrjones** [comment]
👋 Hi @asteiker, that would be fantastic! Thank you! Please feel welcome to open a PR and/or reach out with questions
