### ISSUE TITLE
Add website and information in GitHub sidebar

### ISSUE THREAD

**Issue by maxrjones** [ESIPFed/esds-community-guide#7]
It would be helpful to add the website and about info to the sidebar on GitHub to facilitate navigation to the draft site.

![image](https://user-images.githubusercontent.com/14077947/197224284-e15f4909-a2ba-4fdb-b42b-7787391b9d3b.png)

**Comment by doug-newman-nasa** [comment]
I've got this one.

**Comment by maxrjones** [comment]
@doug-newman-nasa Annie Burgess gave you the necessary permissions to make these changes

**Comment by doug-newman-nasa** [comment]
Side bar updated. Please review. No PR as it is part of the repo config.
